### PR TITLE
Redone style of README.md

### PR DESCRIPTION
**Pull request by Jake-Grafton**
The style changes were done for easier reading and comprehension. The removal of the **hardware mod** section was to improve reading flow as it felt out of place in the main README. The section was preserved however as it is now located at /docs/hardware-mod.md

### CODE REVIEW

**Comment by ZerBea** [comment]
Great, nice improvement. Merged. Thanks.

Unfortunately I don't have much time to work on README or the docs.
The Linux Kernel Tree driver tests, especially compiling and testing the Linux Kernel or cross-compiling OpenWRT is very time-consuming.
The same applies to the new rtw88 (USB) driver, which is on the right track.

**Comment by Jake-Grafton** [comment]
@ZerBea 

I'm glad to hear about how hopeful you are regarding integration of the rtl8812au device into rtw88.
It'd be nice for this shiny new adapter to be able to replace my monitor-mode capable rtl8822au. :P

If you or any other devs you work with need improvements when it comes to READMEs or documentation, let me know.
I'd be glad to write some new documents or improve on existing docs. :)

**Comment by Jake-Grafton** [comment]
@strasharo
[This.](https://www.amazon.com/ALFA-AWUS036ACH-%E3%80%90Type-C%E3%80%91-Long-Range-Dual-Band/dp/B08SJC78FH)

**Comment by ZerBea** [comment]
This is the reference for the rtw88 driver (exclude 8812au):
https://github.com/morrownr/USB-WiFi/issues/430
https://github.com/morrownr/8821au-20210708/issues/133

include 8812au:
https://github.com/lwfinger/rtw88

**Comment by ZerBea** [comment]
BTW:
Instead of patching hundreds of drivers which grow in the wildness, my favorite way is to bring them into the Linux Trees.
Nick ([morrownr](morrownrhttps://github.com/morrownr/USB-WiFi/discussions)) is on the right track.

**Comment by Jake-Grafton** [comment]
@ZerBea 
Do you have any resources for learning how to write/patch drivers for Linux based systems?
I'm new to the C language and I'd like to learn so I can contribute actual code instead of bug reports and docs.

**Comment by ZerBea** [comment]
This is a question that is very difficult to answer.
I'm a retired signals & crypto analyst. All my knowledge comes from my training and more than 35 years of experience in this job.
And I'm still learning (every time a new kernel has been released).
Beside C:
https://www.geeksforgeeks.org/c-programming-language/

knowledge about the Linux Kernel is mandatory:
https://www.kernel.org/doc/html/latest/

As well as 802.11 protocol stuff;
https://mrncciew.com/
https://www.oreilly.com/library/view/80211-wireless-networks/0596100523/

It is good to monitor the Linux Wireless Mailing List;
https://patchwork.kernel.org/project/linux-wireless/list/

And the Linux Kernel itself:
https://www.kernel.org/

To get practice, I suggest to run hcxdumptool and in parallel Wireshark or tshark on the same interface.
Than do some code changes or BPF changes and monitor the out put again.
To monitor the control communication between hcxdumptool and the driver activate nlmon and monitor this traffic by tshark or Wireshark.

**Comment by Jake-Grafton** [comment]
@ZerBea
I'm very well versed in Linux and it's many intricacies.
Thanks for the resources and recommendations. :)

**Comment by ZerBea** [comment]
Great. I love it too, to compile, to install and to configure Linux from scratch.
That include the Raspberry Pi Zero (no W no WH) running OpenWRT (compiled and configured via toolchain).

**Pull request merged**
