### PR TITLE
Addition of example.md

### PR DESCRIPTION
**Pull request by Jake-Grafton**
This commit contains a new document that showcases an example attack on a test AP that I own.

### CODE REVIEW

**Comment by ZerBea** [comment]
Looking good so far, thanks.

But the usage of the BPF is misleading.

This are simple BPF's
```
Target: 00c0cab035be
simple BPF to attack this target: "wlan addr 3 00c0cab035be"
simple BPF to protect this target: "not wlan addr 3 00c0cab035be"
```

This is a an advanced BPF, because it allows hcxdumptool to interact on BROADCAST MACs.
`advanced BPF to attack this target and to allow to handle BROADCAST frames: "wlan addr 3 00c0cab035be or wlan addr3 ffffffffffff"`

While this BPF is useless:
```
The full command to create a BPF to _protect_ 00c0cab035be would be as follows:
hcxdumptool --bpfc="not wlan addr3 00c0cab035be or wlan addr3 ffffffffffff" >> protect.bpf
```
"not wlan addr3 00c0cab035be" == this MAC will be filtered out and all other MACs are allowed - that include the BROADCAST MAC ffffffffffff - so, no need to add  "or wlan addr3 ffffffffffff"

Please note:
hcxdumptool use BLOCK ACK frames to detect connected CLIENTs. This frames do not have an addr 3.
Using this attack filter "wlan addr 3 00c0cab035be" they are filtered out.
To include them to an attack filter: "wlan addr 1 00c0cab035be or wlan addr 2 00c0cab035be or wlan addr 3 00c0cab035be"

Not merged because usage of the BPF is misleading.

**Comment by Jake-Grafton** [comment]
Ok, I understand. I'll change the content so it is actually correct.
I'm slightly confused as the output of `hcxdumptool --help` and `hcxdumptool -h` do not mention wlan addr 1, wlan addr 2, or wlan addr 3.
Do you want me to update the hcxdumptool `--help/-h` or do you want to do that?

**Comment by ZerBea** [comment]
https://networkengineering.stackexchange.com/questions/25100/four-layer-2-addresses-in-802-11-frame-header

**Comment by ZerBea** [comment]
Some tools sue command line options to filter a BSSID (--bssid=11:22:33:44:55:66).
That's not really flexible.
hcxdumptool allows to apply a BPF. That is extreme fast (running in kernel space) and allows to filter nearly everything (by MACs on addr1, 2, 3, 4 as well as frames by types or by content) - without changing hcxdumptools source code!

**Comment by Jake-Grafton** [comment]
@ZerBea 
The requested changes have been made. :)

**Comment by ZerBea** [comment]
Now its fine. Thanks. Merged.

**Comment by Jake-Grafton** [comment]
@ZerBea 
I just tried to use `hcxdumptool --bpfc="not wlan addr 3 112233445566" (112233445566 is a placeholder MAC) and hcxdumptool threw an error stating that it couldn't compile the BPF.
Ex:
```
~ $ hcxdumptool --bpfc="not wlan addr 3 e45f0166cd50"
failed to compile BPF
```

**Comment by ZerBea** [comment]
BTW:
I've added "Detailed knowledge of Bolean Operators" to requirements section of README.md.

Correct is "wlan addx" and not wlan "addr x" - that was an ugly copy and paste error.

**Comment by Jake-Grafton** [comment]
I'll open another pull request with fixed BPF syntax. Gimme a few.

**Pull request merged**
