### PR TITLE
Add new option --eaptlstun to establish TLS tunnel over EAP

### PR DESCRIPTION
**Pull request by n0w1re**
This function establishes a TLS tunnel over EAP, when there is a PEAP request send out with an --eapreq sequence to connecting clients using WPA Enterprise and the client accepts this request. Further EAP requests will be send through this tunnel as EAP Phase 2 authentication packets.
It is mandatory to pass a TLS server certificate in PEM format and the server key to the respective options --eap_server_cert and --eap_server_key.
New option --eapoleaptimeout sets the overall timeout for an entire EAP connection sequence.

- a request to return a possibly available client certificate is send during handshake
- maximum negotiated TLS version is intentionally limited to TLSv1.2 to receive an unencrypted client certificate to store to the pcapng file
- new function in process_fd() that resends packets with RETRY flag if there is no ACK received within PACKET_RESEND_TIMER_USEC for a maximum of PACKET_RESEND_COUNT_MAX times, applies only to EAP request packets sent with send_eap()
- new process80211deauth() to shutdown TLS connection when receiving DEAUTH from client
- new status flags for --enable_status: 512 EAP and 1024 EAP NAK, flag 1 only shows EAPOL KEY messages
- new termination flag for --eapreq :T to shutdown TLS connection

usage:
`--eaptlstun                       : activate TLS tunnel negotiation and Phase 2 EAP requests when requesting PEAP using --eapreq`
`                                          requires --eap_server_cert and --eap_server_key`
`--eap_server_cert=<server.pem>     : EAP TLS tunnel Server cert PEM file`
`--eap_server_key=<server.key>       : EAP TLS tunnel Server private key file`
`--eapoleaptimeout=<digit>             : set EAPOL EAP TIMEOUT (microseconds) over entire request sequence default: 2500000`
`--enable_status=<digit> ...  1: EAPOL, 512: EAP, 1024: EAP NAK`

### CODE REVIEW

**Comment by ZerBea** [comment]
Thanks. Great improvement.

**Comment by ZerBea** [comment]
After some additional tests, we can move to v6.1.3

**Comment by RealEnder** [comment]
Can we generate keypair on fly in addition to --eap_server_cert and --eap_server_key? Best case in this scenario will be to sniff the presented public key from the AP and to use the certificate properties (DN/CN/OIDs...) for the new cert.

**Comment by n0w1re** [comment]
@RealEnder That is a good idea. Some clients might check those if they don't just check the CA or are ok with a self-signed cert.

**Comment by ZerBea** [comment]
I think about it to move the examples from --help to the man page. That will keep --help small.

**Comment by RealEnder** [comment]
@ZerBea examples should be easy accessible online. man page is good though, maybe with additional EXAMPLES file

**Pull request merged**
