### PR TITLE
replace some magic numbers in writegpwpl()

### PR DESCRIPTION
**Pull request by gemesa**
Replaced some magic numbers in `writegpwpl()`.

### CODE REVIEW

**Comment by ZerBea** [comment]
Great. Makes it more readable. Thanks.
Merged

**Comment by ZerBea** [comment]
BTW:
How is your u-blox performing?

**Comment by gemesa** [comment]
So far I only tried direct access which was working ok so I had no reason to try gpsd but I will test it tomorrow also then. My u-blox is only working when I am outside my apartment but its too late for that for today, so I will check tomorrow.

**Comment by ZerBea** [comment]
No problem at all. It was just a question because I like to know what is better: direct ACCESS or GPSD.
I prefer direct ACCESS.

**Comment by ZerBea** [comment]
I fully agree. GPSD NMEA0183 is noisy and GPSD JSON is extreme noisy.
Thanks.

**Pull request merged**
