### PR TITLE
Changes to README.md and addition of BPF.md

### PR DESCRIPTION
**Pull request by Jake-Grafton**
README.md
-------------------
The changes to `README.md` are just fixing formatting errors and simplifying the installation via a package manager. The removal of the `Android` section under the `Install Via Package Manager` section is due to the fact that it appears to be incomplete. The changes also include instructions that tell the user how to install the dependencies `make gcc libpcap libpcap-dev` with any package manager/Linux distribution.

BPF.md
-----------
This file contains a guide that instructs the user how to create a `Berkeley Packet Filter` to protect and attack certain networks.
The guide was cobbled together from all sorts of sources so if I got any commands wrong, please correct me.

### CODE REVIEW

**Comment by ZerBea** [comment]
Not merged:
1) this is not a beginner zone - I don't want to add basic stuff to REAME.md
2) the examples are wrong

- sudo is not mandatory on IEEE802_11_RADIO
- snaplen (65535) is wrong
- ETHLEN should always be 6 bytes

**Comment by ZerBea** [comment]
Please remove the entire BPF lesson and I'm going to merge it.

**Comment by Jake-Grafton** [comment]
The BPF.md file has been removed and a new pull request has been opened. #404

**Comment by Jake-Grafton** [comment]
I understand why you don't want to have BPF.md merged as you see it as unfit for a plethora of reasons. Out of curiosity, what is the correct snaplen?

**Comment by ZerBea** [comment]
As of today, I'm testing a snaplen of 1024 bytes.
Running the build in BPF compiler, hcxdumptool will take the correct one
Running hcxdumptool --help will print the an  example:
`$ tcpdump -s 1024 -y IEEE802_11_RADIO wlan addr3 112233445566 -ddd > filter.bpf`

If you take a look at the adapter tests, you can imagine why it is not a good idea to write a tutorial about BPF:
`bpfc="(not type ctl subtype ack and not type ctl subtype rts and not type ctl subtype cts) and (wlan addr3 08:96:d7:98:e1:9e or wlan addr2 08:96:d7:98:e1:9e or wlan addr1 08:96:d7:98:e1:9e or wlan addr2 00:e6:2d:02:2a:87 or wlan addr1 00:e6:2d:02:2a:87 or wlan addr3 ff:ff:ff:ff:ff:ff)" > target.bpfc`

**Comment by Jake-Grafton** [comment]
I see. Thanks for the help ZerBea!

**Pull request closed without merging**
